<a href="https://colab.research.google.com/github/Mehradtavana/python_Hands_on/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
matrix_one = np.ones((2,2))
print(matrix_one)
matrix_zero = np.zeros((2,2))
print(matrix_zero)
matrix_identify = np.eye(2,2)
print(matrix_identify)

arr = np.array([10.2567,25.3436,3.6335,4.5621])
np.round(arr,2) #we can specify the number of float (default is zero)

#linspace(a,b,c) generate an array that start from a and end b with the c elements
np.linspace(0,10,5)

#Numpy reshape function --> array.reshape(shape)
arr.reshape(2,2)

#Numpy full function --> np.full((2,3),4) (shape, fill_value)
# np.full((2,3),4)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]


array([[10.2567, 25.3436],
       [ 3.6335,  4.5621]])

In [3]:
data['column_name'].value_counts().plot(kind='bar')  # pie, line
# value_counts() function is use to return the value for different classes 
# present in the column of a dataset

NameError: ignored