<a href="https://colab.research.google.com/github/Mehradtavana/python_Hands_on/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
matrix_one = np.ones((2,2))
print(matrix_one)
matrix_zero = np.zeros((2,2))
print(matrix_zero)
matrix_identify = np.eye(2,2)
print(matrix_identify)

arr = np.array([10.2567,25.3436,3.6335,4.5621])
np.round(arr,2) #we can specify the number of float (default is zero)

#linspace(a,b,c) generate an array that start from a and end b with the c elements
np.linspace(0,10,5)

#Numpy reshape function --> array.reshape(shape)
arr.reshape(2,2)

#Numpy full function --> np.full((2,3),4) (shape, fill_value)
# np.full((2,3),4)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]


array([[10.2567, 25.3436],
       [ 3.6335,  4.5621]])

# Practice Numpy
* Consider an one dimensional array Z, build a two dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1(last row should be (Z[-3],Z[-2],Z[-1])? and create 4 sub arrays with the created 2 dimensional array.

In [9]:
arr = np.array([12,11,13,14,17,27,38,10.2567,25.3436])
arr1 = np.reshape(arr,(3,3))
arr2 = np.reshape(arr1,(4,3))
arr2 = np.split(arr1,4,axis=1)
print(arr1)
print(arr2)

ValueError: ignored

In [ ]:
data['column_name'].value_counts().plot(kind='bar')  # pie, line
# value_counts() function is use to return the value for different classes 
# present in the column of a dataset

NameError: ignored

In [2]:
time_series =  pd.date_range('1/1/2020',periods=20)
df = pd.DataFrame(np.random.randn(20,5),  index=time_series, columns=['column1','column2','column3','column4','column5'])
# 20 refers to the number of rows and 5 refers to the number of columns

In [3]:
print(df)
print(df['column1'])
print(df[['column1','column2','column3']]) # Note the difference of use square 
# brackets while accessing single column and multiple columns

# timeseries specific indexing
col1 = df['column1']
col1[time_series[0]] # indexing start from zero


# DataFrame.LOC attribute access a group of rows or columns by labels in 
# the given dataframe
x = pd.DataFrame({'x':[1,2,3], 'y':[3,4,5]})
print(x)
x.loc[1] = {'x':9,'y':99} # change the value in associate row
# x.loc['x'] = [5,9,6]
print(x)


             column1   column2   column3   column4   column5
2020-01-01 -0.101633  1.016931  2.883122  0.796771  1.741124
2020-01-02  0.063875 -0.606912 -2.327014  1.428106 -1.900171
2020-01-03 -0.604437 -0.229859  0.034528 -0.793805  0.233221
2020-01-04  1.807428  1.038485  1.859939  1.323152  1.892306
2020-01-05  0.627093  1.379991 -1.794026 -0.846179  0.509529
2020-01-06 -0.265744  0.976051 -0.069619 -1.944816 -0.377736
2020-01-07  1.471073 -0.247057  1.222032 -1.046059  1.250665
2020-01-08  0.634519 -0.245080 -0.684808  0.040445 -0.247829
2020-01-09  1.175556  0.166598  0.582538  0.571971 -0.133400
2020-01-10 -0.537176  0.361590  0.405562  0.301380  0.175038
2020-01-11 -0.455706 -1.086495 -0.418891 -0.923070 -1.558148
2020-01-12 -1.167530  0.797904  0.246255  0.736901 -0.135433
2020-01-13  1.139018  0.774936  2.032355  1.135689 -1.079217
2020-01-14  1.402108  1.204298  0.424208 -1.272218  0.119466
2020-01-15  0.476440  0.524992  0.353006 -0.271145 -0.645971
2020-01-16  0.355004 -1.

In [ ]:
# Slicing
df.iloc[:5,:2]
df[::3] # every columns but not all rows the last number show the steps in rows

column1   column2   column3   column4   column5
2020-01-01 -0.091323  0.994347 -1.132367 -0.909186  0.785033
2020-01-04 -0.471747 -1.265115  0.664556  0.410974  1.031069
2020-01-07 -0.672988 -1.658640  2.000286  0.095461 -0.500894
2020-01-10  0.926295 -0.702014  0.901644 -0.452082 -2.299609
2020-01-13  0.040640 -0.333046  0.484581 -0.071910 -1.650983
2020-01-16 -0.661770  0.069045  1.041531  0.231877  0.453119
2020-01-19 -0.397742 -1.125112 -0.452272  0.974674  0.114546

In [ ]:
# Filtering
df[(df['column2']<0)&(df['column3']>0)][['column4','column5']] 
# check the situation in col2 and col3 and print satisfy row of col4 and col5

column4   column5
2020-01-04  0.410974  1.031069
2020-01-05  0.636051 -0.112427
2020-01-07  0.095461 -0.500894
2020-01-10 -0.452082 -2.299609
2020-01-13 -0.071910 -1.650983
2020-01-14 -1.069051  0.457853
2020-01-15  0.425069 -0.186066

# Merging DataFrame in pandas
* Process of bringing two datasets together into one, and aligning the rows from each based on common attributes or columns
* The words merge and join are used interchangeably in pandas

## There are four types of joins in python
### Inner Join
* combines two dataframes based on a common key and returns a dataframe that contains only **rows** that have matching values in both of the original dataframes (Same as SQL)
### Outter Join
* Returns all those records which either have a match in the left or right dataframe
* When rows in both the dataframes do not match, the resulting dataframe will have **NaN** for every column of the dataframe that lacks a matching row.
### Left Join
* returns a dataframe containing all rows of left dataframe.
* All the non-matching rows of the left dataframe contain **NaN** for the columns in the right dataframe.
### Right Join
* returns a dataframe containing all rows of right dataframe.
* All the non-matching rows of the right dataframe contain **NaN** for the columns in the left dataframe.

## python code
merge_dataframe = pd.merge(data1,data2,on = '[the same column in both dataframe]', how = 'inner')

# Concatenation
* Concat() function of pandas is used to concatenate the dataframes
* axis = 0, indicates concatenation along the row
* we can use append() funcation df = df1.append(df2) \n df = df.reset_index() \n df=df.drop(['index'],axis = 1)
* Important point the column should be equal to use concatinate

# Map() function
* calls the specified function for each item of an iterable and returns a list of results

# change data type in pandas
* df['x'].astype(int)

# DataFrame.from_items
* From_items is used to create dataframe out of dictionary

In [ ]:
# lets define a function that divide the number to 10
def function(x):
  return x/10

data['column']=data['column'].map(function) # we can use map() function for series
# it means it can't be run in more than one column
data[['col1','col2']] = data[['col1','col2']].apply(function) # with apply() we can apply our function for dataframe
# insist using defined function in apply() or map() we can use lambda
data['col1'] = data['col1'].map(lambda x: x/10)